# Generated by Django 2.1.15 on 2023-12-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20231213_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(default='nothing to say', max_length=500),
        ),
    ]
