# Generated by Django 2.1.15 on 2023-12-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
